### ISSUE TITLE
Getting 500 instead of 401 on login for unauthorized valid pam user

### ISSUE THREAD

**Issue by mistigi** [vmware-archive/salt-api#129]
When I am trying to log in with a user that is not authorized through `external_auth` I am getting HTTP response code 500, I would expect to get 401 instead. However this is a valid system user with a valid password.

`X-Auth-Token` is also returned with this response.

On the other hand, when trying to log in with same user but specifying invalid password works as expected, i.e. response code is 401

```
/etc/salt/master:
rest_cherrypy:
 port: 8388
 ssl_crt: /etc/salt/pki/master/saltmaster0172.com.crt
 ssl_key: /etc/salt/pki/master/saltmaster0172.com.key


external_auth:
  pam:
    saltdev:
      - .*
```

```
           Salt: 0.17.2
         Python: 2.7.3 (default, Sep 26 2013, 20:03:06)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2

salt-api version is 0.8.3
```

```
#curl --insecure -si https://localhost:8388/login \
-H "Accept: application/json" -d username='validpamuser' \
-d password='validpassword' -d eauth='pam' 

HTTP/1.1 500 Internal Server Error
Content-Length: 57
Vary: Accept-Encoding
X-Auth-Token: e20cc33da147e73a313818536de0aa0735ea79ce
Allow: GET, HEAD, POST
Date: Sun, 01 Dec 2013 17:08:03 GMT
Access-Control-Allow-Origin: *
Server: CherryPy/3.2.2
Content-Type: application/json
Set-Cookie: session_id=e20cc33da147e73a313818536de0aa0735ea79ce; expires=Mon, 02 Dec 2013 03:08:03 GMT; Path=/

{"status": 500, "return": "An unexpected error occurred"}
```

```
2013-12-01 17:08:03,608 [salt.loaded.ext.netapi.rest_cherrypy.app][DEBUG   ] Error while processing request for: /login
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 255, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 874, in POST
    perms = self.opts['external_auth'][token['eauth']]['*']
KeyError: '*'
2013-12-01 17:08:03,609 [cherrypy.access.43607376][INFO    ] 127.0.0.1 - - [01/Dec/2013:17:08:03] "POST /login HTTP/1.1" 500 57 "" "curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3"
```

**Comment by whiteinge** [comment]
This is the same problem as saltstack/salt-ui#31 and requires a small change in Salt core. (Basically it just needs to raise a different exception so salt-api can tell the difference between general failures and authentication/authorization failures.)

That said, issue saltstack/salt-ui#31 needed a kick in the pants so thanks for filing this. :-)

Ninja-edit: Er, scratch that. Looks like the salt-ui project had a ticket for this but not salt-api...

**Comment by whiteinge** [comment]
Ok, found the issue number in Salt core. It is saltstack/salt#6420. Sorry for all the cross-referencing waffling. We need to get this fixed. :-P

**Comment by wenchangming211** [comment]
Hello, I have encountered this problem, how can I solve it?
