### ISSUE TITLE
 'unicode' object does not support item assignment

### ISSUE THREAD

**Issue by syphernl** [vmware-archive/salt-api#136]
With the latest revision the API is throwing traceback due to unicode objects

```
[DEBUG   ] Error while processing request for: /run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 273, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.4-py2.7.egg/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 1034, in POST
    'return': list(self.exec_lowstate()),
  File "/usr/local/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 976, in exec_lowstate
    yield self.api.run(chunk)
  File "/usr/local/lib/python2.7/dist-packages/saltapi/__init__.py", line 41, in run
    low['client'] = 'async'
TypeError: 'unicode' object does not support item assignment
```

I'm doing an `manage.status` via the runner what is resulting in above traceback in the API process and an HTTP 500 being returned.

**Comment by whiteinge** [comment]
Thanks for filing this. I committed a change during SaltConf in a rush and missed the `/run` URL. That commit also had another mistake so I will revert it.
