### ISSUE TITLE
I can get token with wrong passwd

### ISSUE THREAD

**Issue by fmnisme** [vmware-archive/salt-api#162]
```
salt-api-0.8.3-1.el5

 salt --versions-report
           Salt: 2014.1.11
         Python: 2.6.8 (unknown, Nov  7 2012, 14:47:45)
         Jinja2: 2.5.5
       M2Crypto: 0.21.1
 msgpack-python: 0.1.12
   msgpack-pure: Not Installed
       pycrypto: 2.3
         PyYAML: 3.08
          PyZMQ: 14.1.1
            ZMQ: 4.0.4
```

```
def login():
    base_url=r'http://192.168.1.100:4507'
    headers={"Accept":"application/json"}
    data={'username':'user1',
          'password':'passwd_wrong'
                     '',
          'eauth':'pam'}
    login_url=r'%s/login'%(base_url)
    res=requests.post(login_url,data,headers=headers)
    print res.text
```

output:
`{"return": [{"perms": ["gboss.*"], "start": 1413272640.4375319, "token": "2c6f1ccd3964bb2276a41a1a75f12bc3b42ad673", "expire": 1413315840.4375329, "user": "user1", "eauth": "pam"}]}`

**Comment by whiteinge** [comment]
What does your `external_auth` configuration look like? Are you actually able to run any functions in the `gboss` module using that token?

**Comment by fmnisme** [comment]
@whiteinge 

```
external_auth:
  pam:
    user1:
        - 'gboss.*'
        - 'test.*'
```

I  actually able to run any functions in the gboss module using that token.
when I `rm /var/cache/salt/master/tokens/ -rf` and run login() func again,it return those error：

```
{"status": 500, "return": "Traceback (most recent call last):\n  File \"/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py\", line 255, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)\n  File \"/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py\", line 34, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py\", line 861, in POST\n    token = self.auth.mk_token(creds)\n  File \"/usr/lib/python2.6/site-packages/salt/auth/__init__.py\", line 123, in mk_token\n    with salt.utils.fopen(t_path, 'w+b') as fp_:\n  File \"/usr/lib/python2.6/site-packages/salt/utils/__init__.py\", line 1069, in fopen\n    fhandle = open(*args, **kwargs)\nIOError: [Errno 2] No such file or directory: '/var/cache/salt/master/tokens/ff33781607ee1a8fac0883b36fa58cae'\n"}

```

It should get a new token ,but  seems to use the old one.

**Comment by pass-by-value** [comment]
Hi @fmnisme 

Looks like you have an older version of salt api installed. 

``` shell
vagrant@vagrant-ubuntu-trusty-64:~$ pip install salt-api
vagrant@vagrant-ubuntu-trusty-64:~$ salt-api --version
salt-api 0.8.4.1
vagrant@vagrant-ubuntu-trusty-64:~$ salt --versions-report
           Salt: 2014.1.11
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.4
vagrant@vagrant-ubuntu-trusty-64:~$
```

With this version I am able to get a `401 Unauthorized` with a bad password.

``` shell
vagrant@vagrant-ubuntu-trusty-64:~$ curl -si localhost:8000/login \
>         -H "Accept: application/json" \
>         -d username='vagrant' \
>         -d password='wrong_password' \
>         -d eauth='pam'
HTTP/1.1 401 Unauthorized
Content-Length: 1640
Vary: Accept-Encoding
Server: CherryPy/3.6.0
Allow: GET, HEAD, POST
Date: Wed, 15 Oct 2014 18:38:48 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=9802d7fcbd2ca0e3596dadc1ca083a80e35a60aa; expires=Thu, 16 Oct 2014 04:38:48 GMT; Path=/

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 292, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saltapi/netapi/rest_cherrypy/app.py", line 1001, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 3.6.0</a>
      </span>
    </div>
    </body>
</html>
```

Installed salt-api via pip.

Are you able to upgrade and check?

Thanks!

**Comment by whiteinge** [comment]
There is an RPM available for download on the release tab in the salt-api
repo. Unfortunately the version in EPEL is out of date. This discrepancy
will be resolved with the next release of Salt since salt-api has been
merged with the main Salt project.

https://github.com/saltstack/salt-api/releases/tag/v0.8.4.1

**Comment by fmnisme** [comment]
@whiteinge @pass-by-value 
I install salt-apiv0.8.4.1 by source code,but it does not work.

**Comment by whiteinge** [comment]
@fmnisme thanks for upgrading to test. Are you saying that release isn't working for you at all or that release does work but does not fix the problem?

**Comment by fmnisme** [comment]
@whiteinge Yes,This problem appears in one of my master Node.The others works well.

**Comment by whiteinge** [comment]
@fmnisme I don't follow. You have more than one salt-api instance or you have one salt-api instance that exhibits the problem?
