### ISSUE TITLE
hi all 

### ISSUE THREAD

**Issue by seshenli** [vmware-archive/salt-api#169]
i have an issue like this 
2015-12-07 14:01:20,104 [cherrypy.error                           ][ERROR   ][9809] [07/Dec/2015:14:01:20] ENGINE Error in 'start' listener <boun
d method Server.start of <cherrypy._cpserver.Server object at 0x221d610>>
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(_args, *_kwargs))
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/servers.py", line 174, in start
    self.wait()
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/servers.py", line 214, in wait
    wait_for_occupied_port(host, port)
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/servers.py", line 427, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
IOError: Port 8090 not bound on '0.0.0.0'

2015-12-07 14:01:20,107 [cherrypy.error                           ][ERROR   ][9809] [07/Dec/2015:14:01:20] ENGINE Shutting down due to error in s
tart listener:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: IOError("Port 8090 not bound on '0.0.0.0'",)

can i fix this ....

**Comment by whiteinge** [comment]
Is the port already in use by another process (or even an old instance of salt-api)? (`netstat -luntp`)

...Or, anything unusual about the IP addresses on that box? Is loopback disabled, or multiple IPs assigned on the same nic? Perhaps you need to specify the [host](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.app.html#module-salt.netapi.rest_cherrypy.app) setting and assign the interface manually?

**Comment by seshenli** [comment]
i changed cherrypy config like host: 192.168.156.55, and this issue fixed.thanks

**Comment by whiteinge** [comment]
Glad you got it! Thanks for replying with an update.
