### ISSUE TITLE
cherrypy._cperror.HTTPError: (401, 'Could not authenticate using provided credentials')

### ISSUE THREAD

**Issue by zwhset** [vmware-archive/salt-api#176]
Traceback
```
 <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/salt/netapi/rest_cherrypy/app.py", line 719, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/salt/netapi/rest_cherrypy/app.py", line 1677, in POST
    'Could not authenticate using provided credentials')
cherrypy._cperror.HTTPError: (401, 'Could not authenticate using provided credentials')
```

I use requests.post method.

```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 10.1.1
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 3.5.3 (default, Mar 14 2017, 17:33:21)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final
```

thanks

**Comment by whiteinge** [comment]
That looks correct. The reason you see the traceback in the output is, I expect, you have `debug: True` in your `rest_cherrypy` config. That traceback is getting handled and a 401 response is returned.

Please double-check that your eauth credentials are correct using the `salt` CLI:

```
salt -a <eauth backend> '*' test.ping
```

Salt will prompt you for a username and password. This must be working for salt-api to authenticate since they use the same code.

**Comment by zwhset** [comment]
Yes, I use tornado disable_ssl:True,and debug:true, port:80  I use pam auth, but i create user and change to passwd.
salt -a pam '*' test.ping is don't woker.
thanks you very much.

**Comment by zwhset** [comment]
master log:
`2017-03-14 18:31:19,005 [salt.master                                                           ][WARNING ][29485] Authentication failure of type "eauth" occurred.
`
Trace:
```
# salt -a pam '*' test.ping -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: Salt-Server-10-50
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: Salt-Server-10-50
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded pam.auth
username: saltapi
password: 
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'Salt-Server-10-50_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 140500480933672 for key ('/etc/salt/pki/master', 'Salt-Server-10-50_master', 'tcp://127.0.0.1:4506', 'clear') and process 30709
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
```


Master conf:
```
rest_tornado:
  port: 80
  debug: True
  disable_ssl: True

external_auth:
  pam:
    saltapi:
      - .*
      - '@wheel'
      - '@runner'
```

becault i disable_ssl : True so i think not check

**Comment by whiteinge** [comment]
Ok. The first step is to get `salt -a pam '*' test.ping` working.

Your `external_auth` configuration looks correct.

* Do you have a local `saltapi` account that you can log into successfully _without_ Salt?
* Is there anything usual about your system PAM configuration?
* Are you authentication via PAM to an external service like LDAP?

**Comment by zwhset** [comment]
1、Ican login saltapi,but after change /sbin/nologin -> /bin/bash
2、i no pam config
3、not use LDAP

1. install CentOS6.5 x86_64 
2. install python3.5.3
3. install pip
4. pip install salt
5. copy https://docs.saltstack.com/en/latest/ref/configuration/master.html conf -> /etc/salt/master and minion
6. useradd saltapi and change passwd
7. change conf
8. run salt-master salt-minion salt-api

**Comment by zwhset** [comment]
PAM conf:

```
#%PAM-1.0
auth [user_unknown=ignore success=ok ignore=ignore default=bad] pam_securetty.so
auth       include      system-auth
account    required     pam_nologin.so
account    include      system-auth
password   include      system-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
session    optional     pam_console.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      system-auth
-session   optional     pam_ck_connector.so
```

**Comment by zwhset** [comment]
Ok, I look Python 3 compatibility https://github.com/saltstack/salt/commit/307a2bcaffec29d306d58b559b71daf9b32001c4
and update pam.py, pro is ok.

```
salt -a pam '*' test.ping
username: saltapi
password: 
Salt-Server-10-50:
    True
```

thank you very very much @whiteinge , you can push to pypi?

**Comment by zwhset** [comment]
now i check login:

```
# curl -si http://localhost/login     -H "Accept: application/json"     -d username='saltapi'     -d password='*******'     -d eauth='pam'
HTTP/1.1 401 Unauthorized
Content-Length: 75
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.4.2
Date: Tue, 14 Mar 2017 12:35:12 GMT
```

error:

> <html><title>401: Unauthorized</title><body>401: Unauthorized</body></html>

use cherry:

```
Traceback (most recent call last):
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 831, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
[ERROR   ] [14/Mar/2017:20:41:42] HTTP 
Traceback (most recent call last):
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/python3.5.3/lib/python3.5/site-packages/cherrypy/_cprequest.py", line 831, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
127.0.0.1 - - [14/Mar/2017:20:41:42] "POST /login HTTP/1.1" 500 1236 "" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
```

**Comment by brandonw352** [comment]
bump
