### ISSUE TITLE
Salt-api on macOS high Sierra

### ISSUE THREAD

**Issue by judexzhu** [vmware-archive/salt-api#182]
Hi, if someone can give me some ideas , that will be very appreciated.

I tried to setup a salt-api development env on my 2017 mpb

(Try to learn to develop a salt-webui with python3 and django2.0)

Python Version : 3.6.4

here is my virtualenv

```
(SaltDev) Judes-MBP:~ jude$ pip freeze

certifi==2017.11.5
chardet==3.0.4
CherryPy==3.2.3
idna==2.6
Jinja2==2.10
MarkupSafe==1.0
msgpack-python==0.5.1
pycrypto==2.6.1
pycryptodome==3.4.7
PyYAML==3.12
pyzmq==16.0.3
requests==2.18.4
salt==2017.7.2
tornado==4.5.3
urllib3==1.22
zmq==0.0.0
``` 

I installed CheeryPy==3.2.3 as doc said. Salt is 2017.7.2

`sudo salt-master -l all` with no issue

here is some log about salt-master

```
.........
[TRACE   ] Loading opts.opts grain
[DEBUG   ] LazyLoaded local_cache.clean_old_jobs
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] This salt-master instance has accepted 0 minion keys.
[TRACE   ] Process manager iteration
[TRACE   ] Process manager iteration
```

`sudo salt-api -l all`

here is some log about the salt-api

```
.......
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Listening for SIGTERM.
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Listening for SIGHUP.
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Listening for SIGUSR1.
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Bus STARTING
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Serving on 0.0.0.0:8080
[INFO    ] [12/Jan/2018:21:58:35] ENGINE Bus STARTED
[TRACE   ] Process manager iteration
[TRACE   ] Process manager iteration
[TRACE   ] Process manager iteration
```

I also create a new `saltapi` account on my macbook with password 'password'

```
(SaltDev) Judes-MBP:~ jude$ id saltapi
uid=502(saltapi) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),701(com.apple.sharepoint.group.1),702(1),100(_lpoperator)
```

here is the `rest_cherrypy` configuration on the `/etc/salt/master`

```
interface: 0.0.0.0

# salt-api configuration
external_auth:
  pam:
    saltapi:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'

rest_cherrypy:
  port: 8080
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key

file_recv: True
```

but when I tried to test the login with follow command, I always get :

```
(SaltDev) Judes-MBP:~ jude$ curl -sSk https://localhost:8080/login -H "Accept: application/json" -d username='saltapi' -d password='password' -d eauth='pam'
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.3</a></span>
    </div>
    </body>
</html>
```

In the meantime , The `saltapi` gave some errors

```
[ERROR   ] [12/Jan/2018:21:59:14] HTTP Traceback (most recent call last):
  File "/Users/jude/.virtualenvs/SaltDev/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 649, in respond
    self.body.process()
  File "/Users/jude/.virtualenvs/SaltDev/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 949, in process
    super(RequestBody, self).process()
  File "/Users/jude/.virtualenvs/SaltDev/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 515, in process
    proc(self)
  File "/Users/jude/.virtualenvs/SaltDev/lib/python3.6/site-packages/salt/netapi/rest_cherrypy/app.py", line 836, in urlencoded_processor
    entity.fp.read(fp_out=contents)
  File "/Users/jude/.virtualenvs/SaltDev/lib/python3.6/site-packages/cherrypy/_cpreqbody.py", line 812, in read
    fp_out.write(data)
TypeError: string argument expected, got 'bytes'

[INFO    ] 127.0.0.1 - - [12/Jan/2018:21:59:14] "POST /login HTTP/1.1" 500 805 "" "curl/7.54.0"
```

but with follow command , I got some feedback

```
(SaltDev) Judes-MBP:~ jude$ curl -sSk https://localhost:8080/
{"return": "Welcome", "clients": ["local", "local_async", "local_batch", "local_subset", "runner", "runner_async", "ssh", "wheel", "wheel_async"]
```

those configuration and commands run well on centos 7 

if there is a way I can fix this, or I need to switch to another way?

Thanks a lot

**Comment by yueyongyue** [comment]
I have the same problem
