### ISSUE TITLE
error: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Su-yj** [vmware-archive/salt-api#189]
When the salt-api service run some time, it will response status 500. And the log was write like this
```
2020-08-31 10:48:27,199 [cherrypy.error   :201 ][ERROR   ][126738] [31/Aug/2020:10:48:27] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1837, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1887, in tick
    s, addr = self.socket.accept()
  File "/usr/lib64/python2.7/socket.py", line 202, in accept
    sock, addr = self._sock.accept()
error: [Errno 24] Too many open files
```

I use the command `lsof`, and find the salt-api is opening too many files. Almost all the files open by it.
I try to count by use the command `lsof | grep salt-api | wc -l` and return `881521`. When I stop the salt-api service, all the files was closed.
```
salt-api   91025 91409           root 8098w     FIFO                0,9       0t0   53061503 pipe
salt-api   91025 91409           root 8099u  a_inode               0,10         0       8506 [eventpoll]
salt-api   91025 91409           root 8100r     FIFO                0,9       0t0   53062450 pipe
salt-api   91025 91409           root 8101w     FIFO                0,9       0t0   53062450 pipe
salt-api   91025 91409           root 8102r     FIFO                0,9       0t0   53064190 pipe
salt-api   91025 91409           root 8103w     FIFO                0,9       0t0   53064190 pipe
salt-api   91025 91409           root 8104u  a_inode               0,10         0       8506 [eventpoll]
salt-api   91025 91409           root 8105u  a_inode               0,10         0       8506 [eventpoll]
salt-api   91025 91409           root 8106r     FIFO                0,9       0t0   53064419 pipe
salt-api   91025 91409           root 8107w     FIFO                0,9       0t0   53064419 pipe
salt-api   91025 91409           root 8108u  a_inode               0,10         0       8506 [eventpoll]
salt-api   91025 91409           root 8109r     FIFO                0,9       0t0   53065719 pipe
salt-api   91025 91409           root 8110w     FIFO                0,9       0t0   53065719 pipe
salt-api   91025 91409           root 8111r     FIFO                0,9       0t0   53068902 pipe
salt-api   91025 91409           root 8112w     FIFO                0,9       0t0   53068902 pipe
salt-api   91025 91409           root 8113u  a_inode               0,10         0       8506 [eventpoll]
salt-api   91025 91409           root 8114u  a_inode               0,10         0       8506 [eventpoll]
```

I've had this problem several times. How can I fix it?

**Comment by Riete** [comment]
I have the same issue, check the salt-api process using fd is 8191, and the default max open file of salt-api is 8192,  I increase it temporarily, is there any better solution？
