### ISSUE TITLE
salt-api "Authentication module threw <nothing>"

### ISSUE THREAD

**Issue by sampipe** [vmware-archive/salt-api#190]
hi,

Hoping for some pointers as am having trouble with authentication failures when trying to /login to salt-api.  Here's what has got me here:

1. Have an existing RHEL6 server which was running old 2016 salt-master and salt-api.  This was working fine with external clients talking to the api and authenticating.
2. upgraded this to the last supported RHEL6 salt version 3000.5.  install was done via standard yum install salt-master salt-api.  I manually merged any changed to the master configs in /etc/salt/master
3. All other functions seem to work but the pam authentication is not.

any pointers are appreciated.

salt -a call
```
[root@XXXXX salt]# salt -a pam '*' test.ping -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: XXXXX
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: lux2063.adm.wd.govt.nz
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded pam.auth
username: saltuser
password:
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'XXXX.nz_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[TRACE   ] Inserted key into loop_instance_map id 139876891603528 for key (u'/etc/salt/pki/master', u'XXXX.nz_master', u'tcp://127.0.0.1:4506', u'clear') and process 12429
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Closing IPCMessageSubscriber instance
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Authentication error occurred.
Authentication error occurred.
```

The master logs do not show much. but the salt.auth DEBUG logs that should show what the error has been thrown in "Authentication module threw %s" is nothing 

```
2021-10-21 15:38:59,642 [salt.transport.zeromq:210 ][DEBUG   ][12429] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
2021-10-21 15:38:59,642 [salt.transport.zeromq:1204][DEBUG   ][12429] Trying to connect to: tcp://127.0.0.1:4506
2021-10-21 15:38:59,700 [salt.utils.lazy                                       :104 ][DEBUG   ][31587] LazyLoaded pam.auth
2021-10-21 15:38:59,704 [salt.auth                                             :112 ][DEBUG   ][31587] Authentication module threw
2021-10-21 15:39:00,843 [salt.auth                                             :312 ][WARNING ][31587] Authentication failure of type "eauth" occurred.
2021-10-21 15:39:00,843 [salt.master                                           :2126][WARNING ][31587] Authentication failure of type "eauth" occurred.
2021-10-21 15:39:00,853 [salt.transport.zeromq:234 ][DEBUG   ][12429] Closing AsyncZeroMQReqChannel instance
2021-10-21 15:39:00,853 [salt.transport.ipc:363 ][DEBUG   ][12429] Closing IPCMessageSubscriber instance
2021-10-21 15:39:00,856 [salt.utils.lazy  :104 ][DEBUG   ][12429] LazyLoaded nested.output
```

salt api config is nothing fancy and the local user is unlocked and the password is correct (I can login)
```
# SALT API Config
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/salt-api/certs/localhost.crt
  ssl_key: /etc/pki/salt-api/certs/localhost.key
  debug: True

external_auth:
  pam:
    saltuser:
      - .*
      - '@runner'
      - '@wheel'
      - '@jobs'
```

salt-api test login showing failure
```

[root@XXXXX bin]# curl -vk https://172.16.XXXX:8000/login -H 'Accept: application/x-yaml' -d username='saltuser' -d password='XXXXXX' -d eauth=pam
* About to connect() to 172.16.64.16 port 8000 (#0)
*   Trying 172.16.64.16...
* Connected to 172.16.64.16 (172.16.64.16) port 8000 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: E=xyz@pdq.net,CN=localhost,O=SaltStack,L=Salt Lake City,ST=Utah,C=US
* 	start date: Jul 14 20:45:31 2015 GMT
* 	expire date: Jul 13 20:45:31 2016 GMT
* 	common name: localhost
* 	issuer: E=xyz@pdq.net,CN=localhost,O=SaltStack,L=Salt Lake City,ST=Utah,C=US
> POST /login HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.1XXXX:8000
> Accept: application/x-yaml
> Content-Length: 53
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 53 out of 53 bytes
< HTTP/1.1 401 Unauthorized
< Content-Length: 1604
< Access-Control-Expose-Headers: GET, POST
< Vary: Accept-Encoding
< Server: CherryPy/5.6.0
< Allow: GET, HEAD, POST
< Access-Control-Allow-Credentials: true
< Date: Thu, 21 Oct 2021 02:45:26 GMT
< Access-Control-Allow-Origin: *
< Content-Type: text/html;charset=utf-8
< Set-Cookie: session_id=ed9c741986cca627c5b31ed7b33b9cb00d79cc71; expires=Thu, 21 Oct 2021 12:45:26 GMT; Path=/
<
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 860, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1882, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
      </span>
    </div>
    </body>
</html>


```
Salt Version:
           Salt: 3000.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, May  8 2020, 22:36:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.10 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.35.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.10 Santiago
```

**Comment by sampipe** [comment]
one update which is odd.. still hunting for a fix.

if I run 'salt-master -l debug' in the foreground from the root user, the salt-api login works as expected.  When I start the salt-master from 'service salt-master start' it doesn't.

both are running as the root user though.
debug in the foreground
```
root      2446  5343  0 16:57 pts/0    00:00:00 /usr/bin/python2.7 /usr/bin/salt-master -l debug
```
started from service
```
root     11903     1  3 17:01 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-master -d
```

**Comment by sampipe** [comment]
This was an. odd one.. we didn't get to the bottom of what has caused this ... we have another server that runs the same config/versions and it works correctly.   We put debug statements into the /usr/lib/python2.7/site-packages/salt/auth/pam.py file to try and work it out with no success.

The odd part of it is that it works fine when we run the salt-master -d from a root interactive terminal.  In the end we have had to work around the issue and running the salt-master like this.. basically changing the init scripts to start the salt-master daemon like this.. 

`su - root -c /bin/bash -c "$SALTMASTER -d $MASTER_ARGS"`
