### ISSUE TITLE
CherryPy Server Error for fun='file.append $dir $string'

### ISSUE THREAD

**Issue by dthom91** [vmware-archive/salt-api#26]
```
       <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/__init__.py", line 141, in hypermedia_handler
    'message': '{0}'.format(exc) if cherrypy.config['debug']
KeyError: 'debug'
```

ping.test works on this target, and the append works correctly if called from the CLI on the Salt master.

**Comment by dthom91** [comment]
User error.
