### ISSUE TITLE
Running with debug=False don't work

### ISSUE THREAD

**Issue by bclermont** [vmware-archive/salt-api#46]
salt-api 0.75

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/saltapi/netapi/rest_cherrypy/__init__.py", line 148, in hypermedia_handler
    index = os.path.join(cherrypy.config['static'], 'index.html')
KeyError: 'static'
```

at this place, cherrypy.config seem to be just cherrypy config... not the rest_cherrypy dict value in master config.

**Comment by whiteinge** [comment]
This has been fixed in the latest Git. I will cut 0.7.6 next week.
