### ISSUE TITLE
CherryPy 500 error when using browser

### ISSUE THREAD

**Issue by porjo** [vmware-archive/salt-api#66]
I've found that if I point my browser (Firefox or Chrome) at http://127.0.0.1:8000 I get a 500 error:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/CherryPy-3.2.2-py2.6.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/saltapi/netapi/rest_cherrypy/app.py", line 220, in hypermedia_handler
    index = os.path.join(cherrypy.config.get('static'), 'index.html')
  File "/usr/lib64/python2.6/posixpath.py", line 67, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Using Curl on the command line (same host) produces the expected 401 error e.g.

```
$ curl -v http://127.0.0.1:8000/
* About to connect() to 127.0.0.1 port 8000 (#0)
*   Trying 127.0.0.1...
* connected
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.27.0
> Host: 127.0.0.1:8000
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 57
< Vary: Accept-Encoding
< Server: CherryPy/3.2.2
< Allow: GET, HEAD, POST
< Date: Mon, 25 Mar 2013 15:37:44 GMT
< Content-Type: application/json
< Www-Authenticate: Session
< Set-Cookie: session_id=aaea7096b7f5af51e6890fc8d04f3f66dd0e520d; expires=Tue, 26 Mar 2013 01:37:44 GMT; Path=/
< 
* Connection #0 to host 127.0.0.1 left intact
{"status": "401 Unauthorized", "return": "Please log in"}* Closing connection #0
```

Log from salt-api can be found here: http://pastebin.com/7tMgLdPF

**Comment by whiteinge** [comment]
Thank you very much for the report!

**Comment by whiteinge** [comment]
Also, thank you for the thorough bug report. That was very helpful. :-)

**Comment by porjo** [comment]
You're welcome - keep up the good work!
